### ISSUE TITLE
add gimap/gimaps as default provider in Session.java

### ISSUE THREAD

**Issue by yuanfang-chen** [ruiaraujo/javamail_android#1]
The classpath way of locating providers does not work well for me on android. It would be so much convenient to add gimap/gimaps as default provider in Session.java, so that messing up with "javamail.x" files are not necessary.

**Comment by ruiaraujo** [comment]
A patch would be lovely.. ;) Otherwise I will take care of it later.

**Comment by yuanfang-chen** [comment]
pull request created.

**Comment by ruiaraujo** [comment]
Thanks for the pull request.
